export type GuideLanguage = 'zh' | 'en' | 'ja';

export const AUTO_COMPACT_AFTER_MS = 3000;
export const AGENT_TAP_DELAY_MS = 370;
export const AGENT_DOUBLE_TAP_MS = 260;
export const HISTORY_KEY = 'companion.history.v2';
export const GUIDE_LANGUAGE_KEY = 'companion.guide.language';
export const VOICE_WAKE_PHRASE = 'hi cherry';
export const VOICE_SEGMENT_MS = 3600;
export const VOICE_RESTART_MS = 180;

export interface ProviderEntity {
  id: string;
  label: string;
  defaultBaseUrl: string;
  defaultModel: string;
  local?: boolean;
  domIds: {
    apiKey: string;
    baseUrl: string;
    model: string;
    combo: string;
    menuButton: string;
    menu: string;
    refresh: string;
  };
}

export const PROVIDERS: ProviderEntity[] = [
  {
    id: 'chat',
    label: '接口 1',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    domIds: {
      apiKey: 'apiKeyInput',
      baseUrl: 'baseUrlInput',
      model: 'modelInput',
      combo: 'modelCombo',
      menuButton: 'modelMenuButton',
      menu: 'modelMenu',
      refresh: 'refreshModelsButton'
    }
  },
  {
    id: 'slot2',
    label: '接口 2',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: '',
    domIds: {
      apiKey: 'imageApiKeyInput',
      baseUrl: 'imageBaseUrlInput',
      model: 'imageModelInput',
      combo: 'imageModelCombo',
      menuButton: 'imageModelMenuButton',
      menu: 'imageModelMenu',
      refresh: 'imageRefreshModelsButton'
    }
  },
  {
    id: 'slot3',
    label: '接口 3',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: '',
    domIds: {
      apiKey: 'claudeApiKeyInput',
      baseUrl: 'claudeBaseUrlInput',
      model: 'claudeModelInput',
      combo: 'claudeModelCombo',
      menuButton: 'claudeModelMenuButton',
      menu: 'claudeModelMenu',
      refresh: 'claudeRefreshModelsButton'
    }
  },
  {
    id: 'local',
    label: '本地模型',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: '',
    local: true,
    domIds: {
      apiKey: 'localApiKeyInput',
      baseUrl: 'localBaseUrlInput',
      model: 'localModelInput',
      combo: 'localModelCombo',
      menuButton: 'localModelMenuButton',
      menu: 'localModelMenu',
      refresh: 'localRefreshModelsButton'
    }
  }
];

export const LAST_PROVIDER_INDEX = PROVIDERS.length - 1;

const zhText = {
  lang: 'zh-CN',
  brandMode: '设置',
  interfaceTitle: '接口',
  waitingKey: '等待 API Key',
  configured: '接口 1 已配置',
  dark: '深色',
  light: '浅色',
  provider: '接口',
  providerMeta: 'Key / URL / 模型',
  apiKey: 'API Key',
  baseUrl: '接口地址',
  model: '模型',
  chooseModel: '选择模型',
  refreshModel: '刷新模型',
  localModel: '本地模型',
  localKeyPlaceholder: '本地服务通常留空',
  workspace: '工作文件夹',
  authorized: '已授权',
  unauthorized: '未授权',
  workspaceLabel: 'AI 可操作目录',
  workspacePlaceholder: '选择文件夹即授权 AI 在其中工作',
  workspaceAuthorizedStatus: '工作文件夹已授权',
  workspaceRevokedStatus: '工作文件夹授权已取消',
  chooseWorkspaceFailed: '选择目录失败',
  commandEnabledStatus: '命令权限已开启',
  commandDisabledStatus: '命令权限已关闭',
  chooseWorkspace: '选择并授权工作文件夹',
  clearWorkspace: '取消授权',
  commandAccess: '允许 AI 在该文件夹内运行调试、构建和发布命令',
  system: '系统',
  startup: '开机自启 CherryPilot',
  lowCpu: '低 CPU 模式',
  enabled: '已开启',
  disabled: '未开启',
  lanShare: '局域网共享',
  lanAllow: '允许同一局域网设备发送资料',
  lanUrlIdle: '开启后显示访问地址',
  lanNoAddress: '已开启，等待网络地址',
  lanDevices: '附近设备',
  lanDevicesEmpty: '暂无可用设备',
  lanDeviceCount: '{count} 台附近设备',
  lanDevicesHint: '点击设备名称，选择文件后直接发送。',
  lanDeviceAddress: '{address}',
  lanRefresh: '刷新设备',
  lanSending: '正在发送到 {device}...',
  lanSent: '已发送 {count} 项到 {device}',
  lanSendFailed: '发送失败',
  guide: '使用说明',
  saveConfig: '保存配置',
  history: '历史询问',
  clear: '清空',
  prompt: '直接提问...',
  noContext: '无上下文',
  waitingQuestion: '等待提问',
  send: '发送',
  openMain: '打开主界面',
  screenshot: '区域截图',
  file: '文件',
  voice: '语音',
  switchModel: '切换模型',
  exit: '退出',
  collapse: '收起为图标',
  pin: '置顶',
  minimize: '最小化',
  close: '关闭',
  expand: '放大',
  modelEmpty: '刷新后选择模型',
  modelSelected: '{provider} 已选择模型',
  refreshingModels: '正在刷新 {provider} 模型',
  modelsFetched: '{provider} 已获取 {count} 个模型',
  noModels: '没有返回模型',
  modelRefreshFailed: '模型刷新失败',
  compactModelNeedConfig: '先在主页面配置接口 Key，然后刷新模型。',
  compactModelFetching: '正在拉取模型...',
  compactModelFetchFailed: '模型拉取失败，检查 Key 和接口地址。',
  providerSelectedModel: '{provider} 已选择 {model}',
  switchedModel: '已切换到 {provider} / {model}',
  saving: '保存中',
  saved: '已保存',
  saveFailed: '保存失败',
  startupReadFailed: '读取失败',
  startupEnabledStatus: '开机自启已开启',
  startupDisabledStatus: '开机自启已关闭',
  startupFailed: '开机自启设置失败',
  lanEnabledStatus: '局域网共享已开启',
  lanDisabledStatus: '局域网共享已关闭',
  lanFailed: '局域网共享失败',
  performanceUpdated: '性能设置已更新',
  lanReceived: '局域网收到 {success} 项。',
  lanReceivedPartial: '局域网收到 {success} 项，{failed} 项失败。',
  historyEmpty: '暂无历史记录',
  contextAnalysis: '基于上下文分析',
  historyQuestion: '历史问题',
  historyBack: '返回历史列表',
  historyExpand: '放大阅读',
  noAnswer: '没有回答内容',
  screenshotChip: '截图',
  fileCount: '{count} 文件',
  textOnly: '文本',
  screenshotSelecting: '等待选择截图区域...',
  screenshotFailed: '截图失败',
  screenshotReady: '截图已加入上下文，已打开预览。',
  screenshotPreview: '截图预览',
  deleteScreenshot: '删除截图',
  closePreview: '关闭预览',
  screenshotDeleted: '截图已删除，不会再作为上下文发送。',
  missingFilePath: '无法读取文件路径：{names}',
  readingFiles: '正在读取文件...',
  filesReadPartial: '已读取 {success} 个文件，{failed} 个失败。',
  filesReadReady: '已读取 {success} 个文件，可以直接提问。',
  filesReadFailed: '读取文件失败',
  needPromptOrContext: '先输入问题，或加入截图/文件。',
  thinking: '正在思考...',
  usingModel: '使用 {model}',
  analysisFailed: '分析失败',
  loadingConfigFailed: '读取配置失败',
  noVoiceCaptured: '没有收到语音',
  transcribingVoice: '正在识别语音...',
  voiceAdded: '语音已加入输入框',
  voiceFailed: '语音识别失败',
  voiceUnavailable: '当前环境不可用语音输入',
  recordingVoice: '正在录音，再点一次麦克风停止',
  microphoneDenied: '麦克风权限被拒绝',
  voiceStartFailed: '语音模式启动失败',
  waitingWake: '等待口令 "hi cherry"...',
  voiceAwake: '已唤醒，请继续说你的需求。',
  keepListening: '{message}\n\n继续监听 "hi cherry"...',
  imagePromptNeeded: '请说出要生成的画面内容。',
  imageGenerating: '正在生成图片...',
  imageGenerated: '已生成图片：{prompt}',
  imageFailed: '生图失败',
  voiceNeed: '已唤醒，请继续说需求。',
  voiceClosed: '语音模式已关闭',
  answeringVoice: '正在回答语音问题...'
};

export type TextKey = keyof typeof zhText;

const enText: Record<TextKey, string> = {
  lang: 'en',
  brandMode: 'Settings',
  interfaceTitle: 'Interfaces',
  waitingKey: 'Waiting for API Key',
  configured: 'Interface 1 configured',
  dark: 'Dark',
  light: 'Light',
  provider: 'Interface',
  providerMeta: 'Key / URL / Model',
  apiKey: 'API Key',
  baseUrl: 'Base URL',
  model: 'Model',
  chooseModel: 'Choose model',
  refreshModel: 'Refresh models',
  localModel: 'Local model',
  localKeyPlaceholder: 'Usually blank for local services',
  workspace: 'Workspace Folder',
  authorized: 'Authorized',
  unauthorized: 'Unauthorized',
  workspaceLabel: 'AI-accessible folder',
  workspacePlaceholder: 'Choose a folder to authorize AI work',
  workspaceAuthorizedStatus: 'Workspace folder authorized',
  workspaceRevokedStatus: 'Workspace access revoked',
  chooseWorkspaceFailed: 'Folder selection failed',
  commandEnabledStatus: 'Command access enabled',
  commandDisabledStatus: 'Command access disabled',
  chooseWorkspace: 'Choose and authorize workspace',
  clearWorkspace: 'Revoke access',
  commandAccess: 'Allow AI to run debug, build, and publish commands in this folder',
  system: 'System',
  startup: 'Launch CherryPilot at startup',
  lowCpu: 'Low CPU mode',
  enabled: 'On',
  disabled: 'Off',
  lanShare: 'LAN Sharing',
  lanAllow: 'Allow devices on this LAN to send materials',
  lanUrlIdle: 'Enable to show the share address',
  lanNoAddress: 'Enabled, waiting for network address',
  lanDevices: 'Nearby devices',
  lanDevicesEmpty: 'No available devices',
  lanDeviceCount: '{count} nearby device(s)',
  lanDevicesHint: 'Click a device, choose files, and send directly.',
  lanDeviceAddress: '{address}',
  lanRefresh: 'Refresh devices',
  lanSending: 'Sending to {device}...',
  lanSent: 'Sent {count} item(s) to {device}',
  lanSendFailed: 'Send failed',
  guide: 'Guide',
  saveConfig: 'Save config',
  history: 'History',
  clear: 'Clear',
  prompt: 'Ask directly...',
  noContext: 'No context',
  waitingQuestion: 'Waiting for a question',
  send: 'Send',
  openMain: 'Open main panel',
  screenshot: 'Screenshot region',
  file: 'File',
  voice: 'Voice',
  switchModel: 'Switch model',
  exit: 'Exit',
  collapse: 'Collapse to icon',
  pin: 'Pin',
  minimize: 'Minimize',
  close: 'Close',
  expand: 'Expand',
  modelEmpty: 'Refresh to choose a model',
  modelSelected: '{provider} selected a model',
  refreshingModels: 'Refreshing {provider} models',
  modelsFetched: '{provider} fetched {count} model(s)',
  noModels: 'No models returned',
  modelRefreshFailed: 'Model refresh failed',
  compactModelNeedConfig: 'Configure an interface key on the main panel, then refresh models.',
  compactModelFetching: 'Fetching models...',
  compactModelFetchFailed: 'Model fetch failed. Check the key and base URL.',
  providerSelectedModel: '{provider} selected {model}',
  switchedModel: 'Switched to {provider} / {model}',
  saving: 'Saving',
  saved: 'Saved',
  saveFailed: 'Save failed',
  startupReadFailed: 'Read failed',
  startupEnabledStatus: 'Startup launch enabled',
  startupDisabledStatus: 'Startup launch disabled',
  startupFailed: 'Startup setting failed',
  lanEnabledStatus: 'LAN sharing enabled',
  lanDisabledStatus: 'LAN sharing disabled',
  lanFailed: 'LAN sharing failed',
  performanceUpdated: 'Performance setting updated',
  lanReceived: 'LAN received {success} item(s).',
  lanReceivedPartial: 'LAN received {success} item(s), {failed} failed.',
  historyEmpty: 'No history yet',
  contextAnalysis: 'Context analysis',
  historyQuestion: 'History question',
  historyBack: 'Back to history',
  historyExpand: 'Expand reading',
  noAnswer: 'No answer content',
  screenshotChip: 'Screenshot',
  fileCount: '{count} file(s)',
  textOnly: 'Text',
  screenshotSelecting: 'Waiting for screenshot region...',
  screenshotFailed: 'Screenshot failed',
  screenshotReady: 'Screenshot added to context. Preview opened.',
  screenshotPreview: 'Screenshot preview',
  deleteScreenshot: 'Delete screenshot',
  closePreview: 'Close preview',
  screenshotDeleted: 'Screenshot deleted. It will not be sent as context.',
  missingFilePath: 'Cannot read file path: {names}',
  readingFiles: 'Reading files...',
  filesReadPartial: 'Read {success} file(s), {failed} failed.',
  filesReadReady: 'Read {success} file(s). Ask directly.',
  filesReadFailed: 'File read failed',
  needPromptOrContext: 'Enter a question or add a screenshot/file.',
  thinking: 'Thinking...',
  usingModel: 'Using {model}',
  analysisFailed: 'Analysis failed',
  loadingConfigFailed: 'Config read failed',
  noVoiceCaptured: 'No voice captured',
  transcribingVoice: 'Transcribing voice...',
  voiceAdded: 'Voice added to input',
  voiceFailed: 'Voice transcription failed',
  voiceUnavailable: 'Voice input is not available in this environment',
  recordingVoice: 'Recording... click mic again to stop',
  microphoneDenied: 'Microphone permission denied',
  voiceStartFailed: 'Voice mode failed to start',
  waitingWake: 'Waiting for "hi cherry"...',
  voiceAwake: 'Awake. Keep speaking your request.',
  keepListening: '{message}\n\nStill listening for "hi cherry"...',
  imagePromptNeeded: 'Say what image you want to generate.',
  imageGenerating: 'Generating image...',
  imageGenerated: 'Generated image: {prompt}',
  imageFailed: 'Image generation failed',
  voiceNeed: 'Awake. Continue with your request.',
  voiceClosed: 'Voice mode closed',
  answeringVoice: 'Answering voice question...'
};

const jaText: Record<TextKey, string> = {
  ...enText,
  lang: 'ja',
  brandMode: '設定',
  interfaceTitle: '接続設定',
  waitingKey: 'API Key 待ち',
  configured: 'インターフェース 1 設定済み',
  dark: 'ダーク',
  light: 'ライト',
  provider: '接続',
  providerMeta: 'Key / URL / モデル',
  chooseModel: 'モデルを選択',
  refreshModel: 'モデルを更新',
  localModel: 'ローカルモデル',
  localKeyPlaceholder: 'ローカルサービスでは通常空欄',
  workspace: '作業フォルダー',
  authorized: '許可済み',
  unauthorized: '未許可',
  workspaceLabel: 'AI が操作できるフォルダー',
  workspacePlaceholder: 'フォルダーを選択して AI の作業を許可',
  chooseWorkspace: '作業フォルダーを選択',
  clearWorkspace: '許可を取り消す',
  system: 'システム',
  startup: 'CherryPilot を自動起動',
  lowCpu: '低 CPU モード',
  enabled: 'オン',
  disabled: 'オフ',
  lanShare: 'LAN 共有',
  lanAllow: '同じ LAN のデバイスから資料を受け取る',
  lanUrlIdle: '有効にすると共有先が表示されます',
  lanNoAddress: '有効です。ネットワークアドレスを待っています',
  lanDevices: '近くのデバイス',
  lanDevicesEmpty: '利用できるデバイスがありません',
  lanDeviceCount: '{count} 台の近くのデバイス',
  lanDevicesHint: 'デバイス名をクリックし、ファイルを選んで直接送信します。',
  lanDeviceAddress: '{address}',
  lanRefresh: 'デバイスを更新',
  lanSending: '{device} に送信中...',
  lanSent: '{count} 件を {device} に送信しました',
  lanSendFailed: '送信に失敗しました',
  guide: 'ガイド',
  saveConfig: '設定を保存',
  history: '履歴',
  clear: 'クリア',
  prompt: '直接質問...',
  noContext: 'コンテキストなし',
  waitingQuestion: '質問待ち',
  send: '送信',
  openMain: 'メイン画面を開く',
  screenshot: '範囲スクリーンショット',
  file: 'ファイル',
  voice: '音声',
  switchModel: 'モデル切替',
  exit: '終了',
  collapse: 'アイコンに折りたたむ',
  pin: '前面固定',
  minimize: '最小化',
  close: '閉じる',
  expand: '拡大'
};

export const UI_TEXT: Record<GuideLanguage, Record<TextKey, string>> = {
  zh: zhText,
  en: enText,
  ja: jaText
};

export const GUIDE_CONTENT: Record<GuideLanguage, Array<[string, string]>> = {
  zh: [
    ['快速提问', '单击悬浮图标展开问答框，输入问题后发送；双击图标打开主界面。'],
    ['截图和文件', '用截图按钮选择屏幕区域，或拖入 PDF、DOCX、Markdown、代码文件，让 AI 结合内容回答。'],
    ['模型配置', '在接口区填写 API Key、接口地址和模型；本地模型可使用 Ollama / LM Studio 的 OpenAI-compatible 地址。'],
    ['工作文件夹', '选择工作文件夹即授权 AI 在该目录内读写、创建项目和打开文件。取消授权后 AI 不能继续访问该目录。'],
    ['命令和自启', '命令权限单独开启后才允许调试、构建和发布命令；开机自启会写入当前系统用户的登录项。']
  ],
  en: [
    ['Quick Ask', 'Click the floating icon to open the compact prompt, then type and send. Double-click the icon to open the main panel.'],
    ['Screenshots and Files', 'Use the screenshot button to select a screen area, or drop PDF, DOCX, Markdown, and source files for context-aware answers.'],
    ['Model Setup', 'Fill in the API key, base URL, and model. Local models can use an OpenAI-compatible Ollama or LM Studio endpoint.'],
    ['Workspace Folder', 'Choosing a workspace folder authorizes AI to read, write, create projects, and open files only inside that folder.'],
    ['Commands and Startup', 'Command access is separate and required for build, debug, and publish commands. Startup launch is registered for the current OS user.']
  ],
  ja: [
    ['クイック質問', 'フローティングアイコンをクリックして質問欄を開き、入力して送信します。ダブルクリックでメイン画面を開きます。'],
    ['スクリーンショットとファイル', '画面範囲を選択するか、PDF、DOCX、Markdown、ソースファイルをドロップして回答に使います。'],
    ['モデル設定', 'API Key、Base URL、モデル名を入力します。ローカルモデルは Ollama / LM Studio の互換エンドポイントを使えます。'],
    ['作業フォルダー', '作業フォルダーを選択すると、その中だけで AI の読み書きとファイル操作を許可します。'],
    ['コマンドと自動起動', 'ビルドやデバッグには別途コマンド許可が必要です。自動起動は現在の OS ユーザーに登録されます。']
  ]
};
